### ISSUE TITLE
Does not see rp

### ISSUE THREAD

**Issue by wegahahegeyha** [HiWord9/RPRenames-fabric#49] opened 2024-03-23 17:11 UTC
The mod does not shows renames. Ive dowloaded rp KSEPSP, and nothing works, but texture itself is changing on renaming by myself. Im using sodium + cit resewn. And even Better Anvil does not see anything. dearchiving pack does not helps.
![изображение_2024-03-23_201102569](https://github.com/HiWord9/RPRenames-fabric/assets/106657170/f8809a0e-9263-4e38-947c-bfdf8af3928d)

**Comment by HiWord9** [comment] 2024-03-23 17:30
Which rprenames version is installed? Which minecraft version do u use? What modloader? Is rp archived or not? Try f3+t ingame

**Comment by wegahahegeyha** [comment] 2024-03-23 17:41
Last mod version from modrinth, mc 1.20.1 (on 1.19.2 was the same issue), i tried archieved rp and unziped folder.

**Comment by HiWord9** [comment] 2024-03-23 17:55
Please execute this: launch minecraft, turn on ksepsp if it is disabled, login to the world in singleplayer and open anvil menu up to state where u see that there is no renames. Next close minecraft and send here log file that is located in path .minecraft/logs/latest.log

**Comment by wegahahegeyha** [comment] 2024-03-23 18:06
[latest.log](https://github.com/HiWord9/RPRenames-fabric/files/14733200/latest.log)

**Comment by HiWord9** [comment] 2024-03-23 18:43
I see its something about zip file. I recommend u to redownload rp from official site.
And btw u are not using the last version of rpr. Ur version is 0.7.1 and 0.7.2 is already published, so mb updating mod will help u.

The problem came directly from reading the zip file, looks like the file is corrupted. I found out that [this line in rpr](https://github.com/HiWord9/RPRenames-fabric/blob/1.20.2/src/main/java/com/HiWord9/RPRenames/util/config/ConfigManager.java#L87) and [this line in better anvil](https://github.com/LopyMine/BetterAnvil/blob/master/src/main/java/net/lopymine/betteranvil/cit/writers/ZipWriter.java#L65) are using the same method to read zip file, so thats why ba could not get access to this pack too.
In 0.8.0 it will be fixed due to changed renames search system where it no longer reads files directly.

If u could do the same process discribed in my last comment but with unziped pack, i would try to help u to solve the problem if it is possible or at least i'd get more info about this bug.

**Comment by wegahahegeyha** [comment] 2024-03-23 18:53
but it was with the unzipped pack. Actually, i have 2 versions. One is old, zipped and disabled, the newest one is unzipped and i used it when was making that log

**Comment by HiWord9** [comment] 2024-03-23 19:07
Then it makes the problem even more worse. For some reason code treats the pack as file, not folder. And looks like the problem is directly with pack file dowloaded on ur computer as ba have this problem too but other ppl have not problem with this pack in general. I hope it will be fixed in 0.8.0 as i said before. 
For now i recommend u to dowload pack from official site and update rpr up to 0.7.2. Also u could try to download not latest version of pack but older, mb something about fresh ver of pack. Also mb something about ur zip archivator application.

I will mention here when 0.8.0 will be published to check is problem will be solved, until then the issue will be left open.

If u will manage to figure out it by urself please let me know here so i could close the issue.

**Comment by wegahahegeyha** [comment] 2024-03-23 19:17
The same bug appeared this older version of this pack, but ur mod works with other rps, so looks like the bug is personaly with this pack. At least it is not critical, it works in my friend's client so i can use mod through him. I will try to use his options.txt and some other config files. Thanks for your time!

**Comment by HiWord9** [comment] 2024-04-01 07:23
It should be fixed in 0.8.0 due to a new system of searching renames so im closing this issue

**Closed as completed by HiWord9** 2024-04-01 07:23 UTC
Labels: 🔥 bug, 📄 config, 🚨 important
