### ISSUE TITLE
Is there gonna be any support for this mod for optifine?

### ISSUE THREAD

**Issue by Animetheemo** [HiWord9/RPRenames-fabric#34] opened 2023-09-19 04:01 UTC
I know a lot of people are switching to Sodium, CIT resewn, and Irirs for their set but I find that CIT resewn and it's broken paths along with the new texture atlas and a bunch of other stuff have made CIT packs difficult to use with CIT resewn. Afterall almost every single one of them was made with Optifine assets and not CIT resewn assets.

I also acknowledge how unstable Optifine and Optifabric are and I as a CIT content creator and others are hoping, praying, wishing that everything could be ported to CIT Resewn asap.

But until CIT resewn is more applicable to more CIT packs, is this mod gonna be supported with Optifine? As of right now it has the 'resource pack limit' crash, if it's not I understand but it'll be suchhh a bummer because this saves soooo much time.

**Comment by HiWord9** [comment] 2023-09-19 04:55
The only problem why u can't use rpr with optifabric is that "failed to reload resources" crash, without it it could work fine, as is on 1.19.2. I hope, wish, praying that I'll understand what should I do to fix it, but for now it is absolutely not-uderstandable thing for me, partly because of OF not having source code.

Apparently the issue is same as "failed to reload resources" issue, so I will mark it as a duplicate.

BUT, I am planning to make a port for forge very very soon, and I hope no problems with optifine will be found there. Sadly it is not how it should be, I mean it won't fix this crash on fabric, but anyways that is all I can.

**Comment by dima-dencep** [comment] 2023-09-19 05:20
https://github.com/Chocohead/OptiFabric/issues/1216

**Comment by Animetheemo** [comment] 2023-09-19 05:35
XD understandable

#hoping wishing and praying that OF will be outdated software completely

**Comment by dima-dencep** [comment] 2023-09-19 05:36
Why

**Comment by Animetheemo** [comment] 2023-09-19 05:39
> Why

Because OFs closed source script makes it difficult to work with for a myriad of mod authors, and with more and more mods coming out to simulate everything OF does it'll be easier for Mod authors and users alike to stop using it all together.

Or at least that's my opinion on it.

**Comment by dima-dencep** [comment] 2023-09-19 05:43
Optifine my beloved 💙💙💙💙💙

**Comment by Animetheemo** [comment] 2023-09-19 05:48
I love optifine and its become a staple, especially because i use CIT packs and no mods. But I can definitely see how difficult it is to work with in the modding community and a combination of Sodium + Iris + CIT resewn could totally replace it in the future

The only reason I and a few others don't switch over to CIT resewn entirely is like i said, it doesn't support some major CIT pack staples, im waiting for it to be more stable then i plan on switching over to fabric mods only.

**Closed as not planned** 2023-09-19 08:48 UTC
Labels: 🏖 extra
