### ISSUE TITLE
crash when you try to use anvil

### ISSUE THREAD

**Issue by papamaionise** [HiWord9/RPRenames-fabric#65] opened 2024-11-13 13:43 UTC
[crash-2024-11-13_01.36.05-client.txt](https://github.com/user-attachments/files/17733403/crash-2024-11-13_01.36.05-client.txt)

**Comment by HiWord9** [comment] 2024-11-13 13:50
Duplicate of #14

Incompatibility with Easy Anvils. 
[This](https://github.com/HiWord9/RPRenames/issues/63#issuecomment-2427160325) may help u if u still need to use easy anvils

**Closed as completed by HiWord9** 2024-11-13 13:50 UTC
Labels: duplicate

**Comment by papamaionise** [comment] 2024-11-13 15:43
ah i c welp ig i'll just wait for the few mods to port to 1.21.1 and then just move to the newer version thanks for your time!

**Comment by HiWord9** [comment] 2024-11-13 18:32
> i'll just wait for the few mods to port to 1.21.1

If anything rprenames on 1.21.1 is still incompatible with easy anvils so u still will have to delete one of those mods (or use them together as described [here](https://github.com/HiWord9/RPRenames/issues/63#issuecomment-2427160325))

**Comment by papamaionise** [comment] 2024-11-14 11:15
> > i'll just wait for the few mods to port to 1.21.1
> 
> If anything rprenames on 1.21.1 is still incompatible with easy anvils so u still will have to delete one of those mods (or use them together as described [here](https://github.com/HiWord9/RPRenames/issues/63#issuecomment-2427160325))

would the compatibility issue ever be resolved in future?
or it's not possible on your end

**Comment by HiWord9** [comment] 2024-11-14 11:17
> would the compatibility issue ever be resolved in future? or it's not possible on your end

I plan to figure it out somewhen
