### ISSUE TITLE
Empty CIT Library

### ISSUE THREAD

**Issue by AlterEghost** [HiWord9/RPRenames-fabric#50] opened 2024-03-31 16:41 UTC
its seems to be half working. 1.20.1 fabric

the menu and everything is here, when i renamed weapons its working. BUT
i can only see the items i discovered by renaming, nothing else.

which means, if i didnt rename nothing yet.....i cant see any custom items.

![rprenames](https://github.com/HiWord9/RPRenames-fabric/assets/51702957/4ad5389f-2993-417f-a4c0-51ef05074517)

**Comment by HiWord9** [comment] 2024-03-31 20:18
Please execute this: launch minecraft, turn on rp you are using if it is disabled, login to the world in singleplayer and open anvil menu up to state where u see that there is no renames. Next close minecraft and send here log file that is located in path .minecraft/logs/latest.log

Also id like to know the name of the pack, and was it archived or not?

And another important thing, does it works with other packs?

Mb it is the same as #49

**Comment by HiWord9** [comment] 2024-03-31 21:26
il mark this one as duplicate of #49 cause both are the same

**Closed as completed** 2024-03-31 21:26 UTC
Labels: ✏ question, duplicate
